<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250501084546 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(
            <<<'SQL'
                ALTER TABLE album ALTER id TYPE INT
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE album ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE media ALTER id TYPE INT
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE media ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE "user" ADD password VARCHAR(60) NOT NULL DEFAULT ''
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE "user" ALTER id TYPE INT
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE "user" ALTER id ADD GENERATED BY DEFAULT AS IDENTITY
                SQL,
        );
        //
        $this->addSql('UPDATE "user" SET password = \'$2y$13$7JS0ehfU8vZhB3Q8o1sPGuoQxkiPGXRGgrAizmNfI5Sgy.Dqt9xoW\' WHERE email = \'ina@zaoui.com\'');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql(
            <<<'SQL'
                ALTER TABLE album ALTER id TYPE INT
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE album ALTER id DROP IDENTITY
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE media ALTER id TYPE INT
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE media ALTER id DROP IDENTITY
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE "user" DROP password
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE "user" ALTER id TYPE INT
                SQL,
        );
        $this->addSql(
            <<<'SQL'
                ALTER TABLE "user" ALTER id DROP IDENTITY
                SQL,
        );
    }
}
